services:
  postgres:
    image: postgres:15
    container_name: eventify_db
    environment:
      POSTGRES_DB: eventify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: malik
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventify_network

networks:
  eventify_network:
    driver: bridge

volumes:
  postgres_data:
